### ISSUE TITLE
Doesn't work since latest version

### ISSUE THREAD

**Issue by Nitradamus** [iwind/gofcgi#2]
Hi, I am using this module in several projects and it just tried to update and failed:

module github.com/iwind/gofcgi@latest found (v0.0.0-20210506081859-17498ab3e9d7), but does not contain package github.com/iwind/gofcgi

I import it with 

import (
	"github.com/iwind/gofcgi"
)

Any idea what i'm doing wrong? Thanks for your time & great project :)

**Comment by iwind** [comment]
I am so Sorry, but now you should retrieve the latest version, and change your code to 
~~~
import (
     ...
    "github.com/iwind/gofcgi/pkg/fcgi"
     ...
)

...
fcgiReq := fcgi.NewRequest()
fcgiReq.SetTimeout(fastcgi.ReadTimeoutDuration())
fcgiReq.SetParams(params)
fcgiReq.SetBody(this.RawReq.Body, uint32(this.requestLength()))
...

~~~

**Comment by Nitradamus** [comment]
Thank you very much, it works again! :)
